# Configuration file for the Sphinx documentation builder.

# -- Project information -----------------------------------------------------

project = 'SeisMonitor'  # Replace with your project's name
copyright = '2025, Emmanuel Castillo'  # Replace with the copyright holder's name
author = 'Emmanuel Castillo'  # Replace with the author's name

# The full version, including alpha/beta/rc tags
release = '0.0.56'  # Replace with your version

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    'sphinx.ext.autodoc',  # Automatically documents code from docstrings
    'sphinx.ext.viewcode',  # Adds links to the source code in the docs
    'sphinx.ext.napoleon',  # To support Google-style docstrings
    'sphinx_rtd_theme',  # To use the Read the Docs theme
]

# The language for content autogenerated by Sphinx. Refer to documentation for a list of language codes.
language = 'en'

# The master toctree document.
master_doc = 'index'

# List of patterns, relative to source directory, that match files and directories
# to ignore when looking for source files.
exclude_patterns = []

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages. See the documentation for a list
# of builtin themes.
html_theme = 'sphinx_rtd_theme'  # The Read the Docs theme

# The name for this set of HTML files. If this is None, it will be the basename
# of the source file.
html_title = project

# Paths that contain custom static files (such as style sheets), relative to this
# directory. They are copied after the built-in static files, so a file named
# "default.css" will override the built-in "default.css".
html_static_path = []

# -- Extension configuration -------------------------------------------------

# If you use autodoc, you may want to add the following:
autodoc_default_flags = ['members', 'undoc-members', 'show-inheritance']

# Napoleon settings for Google-style and NumPy-style docstrings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
